// UA SIM - wraps scraped JSON into a JS global so the game runs from file:// without a server.
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const cards = JSON.parse(readFileSync(join(ROOT, 'data', 'cards.json'), 'utf8'));
const names = JSON.parse(readFileSync(join(ROOT, 'data', 'series-names.json'), 'utf8'));

// keep only fields the game uses; trim trailing whitespace in texts
const slim = cards.map(c => ({
  no: c.cardNo,
  id: c.originalId,
  name: c.name,
  color: (c.color || '').trim() || null,
  type: c.type,
  series: c.series,
  rarity: c.rarity,
  raritytype: c.raritytype || null,
  bp: c.power ?? null,
  ap: c.apCost ?? null,
  need: c.energyCost ?? null,      // required energy
  gen: c.generatedEnergyData ?? null, // energy generation
  trigger: c._trigger || null,
  triggerText: (c._triggerText || '').trim() || null,
  effect: (c.effect || '').trim() || null,
  traits: (c.traits || '').trim() || null,
  img: c.imageLink,
  main: !!c.mainalternate,
}));

const out = `// generated by tools/build-data-js.mjs — do not edit by hand
window.UA_CARDS = ${JSON.stringify(slim)};
window.UA_SERIES_NAMES = ${JSON.stringify(names)};
`;
writeFileSync(join(ROOT, 'data', 'cards.js'), out);
console.log('data/cards.js written:', slim.length, 'cards,', (out.length / 1024 / 1024).toFixed(1), 'MB');
